#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

if [[ "$(uname)" = 'Darwin' ]]; then
    export PATH="/usr/local/opt/coreutils/libexec/gnubin:${PATH}"
fi
export PATH="${PATH}:/home/max/mbin"
