#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
setopt histignorespace

# Add homebrew to the completion path
if [ -d /usr/local/share/zsh/site-functions ]; then
    fpath=("/usr/local/share/zsh/site-functions/" $fpath)
fi

# Add completion for kitty
if type kitty &>/dev/null; then
    kitty + complete setup zsh | source /dev/stdin
fi

# Aliases
alias gpg=gpg2
alias vi=vim
alias history='history 0'
